### ISSUE TITLE
PublishMsg/libwebsocket slow to handle packets?

### ISSUE THREAD

**Issue by maucoen** [robcog-iai/UROSBridge#21]
Hi Andrei,

Excellent plugin, thank you very much for this! I've implemented a Mono, RGBD, and Stereo image publisher to a ROS node (to run ORB-SLAM). These data types are similar to pointcloud2.

I can publish at a max of 2.5MB/s (publishmsg in an AsyncTask), which is about 5Hz on my current image size. This is a publish data rate in the ROS topic. If I try a higher frequency (in Unreal), the ROS topic data rate drops to 1MB/s max, and the publish tasks seem to take WAY longer than at a slightly slower frequency.

I've tried running multiple Handlers but I'm guessing they all connect to the rosbridge node through IP and port and this is the bottleneck?

I'm trying to understand where exactly is the bottleneck, why it is happening and if there's any way to increase the data rate, and/or avoid the sudden drop. I see that libwebsockets runs on a single thread, but I'm not familiar with it, is this the bottleneck?

Any thoughts on what to look at next?  Is there anything I'm missing? Thanks! 

I'll try running 2 instances of rosbridge nodes on different ports in the meantime.

Best,
Mau

**Comment by maucoen** [comment]
I've tried with 2 rosbridge nodes and distributing publish tasks to these 2, and the same drop appears (to around 1MB/s). I don't quite understand how it can drop from 2.5MB to 1MB when slightly increasing the publish task rates. Let me know if you want to discuss in more detail!

**Comment by andreihaidu** [comment]
Hi Mau,

thanks for your interest in the plugin. It is indeed peculiar that the data rate drops. It might be dropping packages if it is publishing to fast? Not sure. The websocket connection module was used (and modified a bit from Unreal). In general it is also pretty ineffective to send large amount of data with this plugin, since it converts everything to json. We are looking into using bson at one point in the future.

I am currently away from an Unreal setup to test this, however to narrow down the issue you could use the CPU profiler from unreal engine, maybe you find out where the issue is (https://docs.unrealengine.com/latest/INT/Engine/Performance/CPU/).

Also what are your FPS when publishing at 5H, and when trying to publish more?

Cheers,
Andrei

**Comment by maucoen** [comment]
Found the culprit! I was looping through the data in ToJsonObject() without need. The base64 encoder already does the job! The pointcloud2.h also has that loop.
