### ISSUE TITLE
Update in new repo (this)

### ISSUE THREAD

**Issue by iamsuperwen** [robcog-iai/UROSBridge#24]
Hello,
I use [UROSBridge@e5a9141](https://github.com/robcog-iai/UROSBridge/tree/e5a9141b80822ebe28008909ee07b9c4dbe66238) with the example code in the /Source folder of [ex-ros-tf-robosim](https://github.com/robcog-iai/RobCoG/tree/ex-ros-tf-robosim), and it works really fine. But when I update to the newest version, just got the error from rosbridge:

> [ERROR][1519990982.357098]: [Client 4] subscribe: ROSString is not a valid type string

I'm receiving String msg from ROS.
I know there's have several changes between two branches, but didn't know where I should revise with the files [(ROSStringSubscriber](https://github.com/robcog-iai/RobCoG/blob/ex-ros-tf-robosim/Source/RobCoG/ROSStringSubscriber.cpp)? [ROSBridgeHandler](https://github.com/robcog-iai/UROSBridge/blob/master/Source/UROSBridge/Public/ROSBridgeHandler.h)? [std_msgs/String](https://github.com/robcog-iai/UROSBridge/blob/master/Source/UROSBridge/Public/std_msgs/String.h)?  or something else?)
Hope someone could give me some hints.
Thanks!!

**Comment by andreihaidu** [comment]
Hi,

yes, sorry, this can happen since all these modules are constantly changing, however usually the ex-ros-tf branch compiles. Can you try again with the current state, also don't forge to update the submodules as well:

"git submodule update --recursive --init" should bring it to the right state.

Let me know if it still does not work.

Cheers,
Andrei
