### ISSUE TITLE
Add support for Point Cloud types

### ISSUE THREAD

**Issue by aaronsnoswell** [robcog-iai/UROSBridge#6]
As a: ROS-Unreal Developer
I want to: Be able to subscribe to sensor_msgs/PointCloud2 message topics in UE4 via ROSBridge
So that: I can view Point Clouds in Unreal

Pull request that accomplishes this on the way...

**Comment by andreihaidu** [comment]
Hi, thanks for the pull request, I added some changes to your message type (https://github.com/robcog-iai/UROSBridge/commit/0b195095e70a3d1885d1a557741e9cabe7c564f2):

 * `Type` changed to `MsgType` (some messages used this name, so to avoid name collisions I have changed it)
 * I added a namespaced version of your message to avoid long names ( `FROSBridgeMsgSensormsgsPointCloud2` becomes `sensor_msgs::PointCloud2` )
 * I changed the variable names to Unreal specific PascalCase
 * and renamed input variables form `_example` to  Unreal specific `InExample`

* Further (https://github.com/robcog-iai/UROSBridge/commit/ef195f57bfb775d11896736e54cec5016c735363) I have finally removed all the non-namespaced message declarations

Hopefully this will not break anything in your code. Let me know if it does.

Looking forward to your point cloud visualization.

Keep in mind, since UROSBridge uses websockets, it transmits data as strings over the network (ros_bridge does not support bson at the moment on websockets) which is very non-optimal for large volume data transmission. We do plan to look into bson support in the future.

Cheers!

**Comment by aaronsnoswell** [comment]
Thanks Andrei!

I appreciate your changes - Don't worry about anything - I'll pull this repo and update my project at my end.

Thanks for the note about performance. I was aware that UROSBridge currently only supports JSON. I have two thoughts regarding this;

1. In my use case I only use ROSBridge to send uncompressed PointCloud2 on a localhost / loopback network link. I use compressed pointclouds when sending the data over an actual network link (WiFi / Ethernet), and even then, apply some pre-processing to decimate the cloud a bit.
2. I am investigating the performance of sending uncompressed PointCloud2 messages via JSON. If network bandwidth turns out to be a bottleneck for me, I would be happy to assist with the development to support ROSBridge connections over BSON in this plugin. I'll let you know how I go by adding more comments below :)

Thanks again!

**Comment by Sanic** [comment]
Just a small note on bson/json performance:
- If i remember correctly, the necessary base64 encoding of binary data in rosbridge takes roughly 30-33% more space than the original data. This might indeed not be a problem on local links
- The main problem might be the computational overhead of the base64 decoding/encoding, as illustrated here: https://github.com/RobotWebTools/rosbridge_suite/issues/169

**Comment by aaronsnoswell** [comment]
Hi @Sanic :) Didn't realise you were over here. I've been using @andreihaidu's plugin rather than the ROSIntegration plugin as it seems a bit more stable :)

- Indeed, the Base64 encoding does take up more space, and has an overhead for decoding.

Interestingly, on a local link, the JSON PointCloud receiving step is not my bottleneck (although it is slow for full-size point clouds) - it turns out parsing the decoded Base64 byte array for rendering in UE4 is actually the slowest part. As this is a rather parallel task I'm going to investigate alternate ways to show the PointCloud that can leverage GPU particles in UE4.

That said, it would still be good to update this repo with ROSBridge BSON support. I might create an issue for ongoing discussions around this.
